title: Notes for Later
description: >-
  Good luck buddy
author: Your Name
baseurl: "/XiuShen"
url: "https://nichkt.github.io"

permalink: /:title/

markdown: kramdown
kramdown:
  input: GFM

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
